[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lantern"
path = "src/main.rs"

[dependencies]
arena = { path = "../arena" }
diagnostic = { path = "../diagnostic" }
parse = { path = "../parse" }
spark = { path = "../spark" }
runtime = { path = "../runtime" }
clap = { version = "4.5.31", features = ["derive"] }

